services:
    mongodb:
        container_name: 'mongo_vdlg'
        image: mongo:latest
        ports:
            - 27017:$MONGO_PORT
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASS
            - MONGO_INITDB_DATABASE=$MONGO_DB
        volumes:
            - ./mongo_data:/data/db
        # restart: always 
volumes:
    mongodb_data:
