apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tremligeiro-customer
  namespace: tremligeiro
  labels:
    app: tremligeiro-customer
    environment: "dev"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tremligeiro-customer
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
